# Generated by Django 3.2.12 on 2022-04-07 13:47

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id_graph', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), size=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'graph',
            },
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id_vertex', models.AutoField(primary_key=True, serialize=False)),
                ('type_vertex', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10), size=None)),
                ('graph_id', models.ForeignKey(db_column='id_graph', on_delete=django.db.models.deletion.CASCADE, to='graphs.graph')),
            ],
            options={
                'db_table': 'vertex',
            },
        ),
    ]
