# Generated by Django 3.2.12 on 2022-04-06 12:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id_graph', models.AutoField(primary_key=True, serialize=False)),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None), size=None)),
            ],
            options={
                'db_table': 'graph',
            },
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id_vertex', models.AutoField(primary_key=True, serialize=False)),
                ('type_vertex', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10), size=None)),
            ],
            options={
                'db_table': 'vertex',
            },
        ),
    ]
