# Generated by Django 3.2.12 on 2022-04-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='graph_id',
            field=models.ForeignKey(db_column='id_graph', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='graphs.graph'),
            preserve_default=False,
        ),
    ]
