# Generated by Django 3.2.12 on 2022-04-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='local_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
