# Generated by Django 3.2.12 on 2022-04-07 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphs', '0002_vertex_graph_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vertex',
            name='graph_id',
            field=models.ForeignKey(db_column='id_graph', on_delete=django.db.models.deletion.CASCADE, to='graphs.graph'),
        ),
    ]
